In [22]:
import numpy as np

# Array Operation

### Arithmetic Operation

In [26]:
a1 = np.array([1, 2,3 ,4 ,5])
a2 = np.array([6, 7, 8, 9, 10])
a1 + a2 

array([ 7,  9, 11, 13, 15])

Here, we have the array with same number of elements, but if we have array with different elements then we will get error

When we are doing any array operation, the size must be same

similarly, we can do *, /, -, //, ** too

### Broadcasting

In [30]:
l = [10, 20, 30, 40, 50]
arr = np.array(l)
l + 10 

TypeError: can only concatenate list (not "int") to list

Here, when we try to add 10 in all the elements of LIST, we get error, and we need to write a code of loop.

But, we can convert the list to array and perform addition in one line Eg: "arr + 10" ; and it is known as broadcasting.

In [33]:
arr + 10

array([20, 30, 40, 50, 60])

In [35]:
arr2 = np.arange(1, 26).reshape(5 ,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [37]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

### Deep and Shallow copy

In [40]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [42]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [44]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

When we do any changed on the array using slice, the main array doesn't change, but in case of list the main array also gets changed, 

And if the default array doesnt change then it is shallow copy and if the main array also gets affected then it is deep copy 

In [47]:
a[4:6] * 10

array([50, 60])

In [49]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
a 
b = a
b [0] = 99

In [53]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

This is deep copy.

When we use the slice, it will create a new location in the RAM, but if we copy the array then the pointer gets changed, the location doesn't change, hence the default array also changed, this is called deep copy

If we dont want deep copy to happen while copying the arrarys then we should use copy function.

b = a  [This is deep copy]

b = a.copy()  [This is shallow copy]

In [58]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
b = a.copy()
b[0] = 1

In [64]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Matrix operations

In [69]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [71]:
A

array([[1, 2],
       [3, 4]])

In [73]:
B

array([[5, 6],
       [7, 8]])

In [75]:
A * B

array([[ 5, 12],
       [21, 32]])

Here, the multiplication was performaed based on the index but not how actual multiply happes in the matrix. 

In [78]:
A @ B # This does actual multiplication of matrix

array([[19, 22],
       [43, 50]])

In [80]:
np.dot(A, B) # We can also perform multiplication like this

array([[19, 22],
       [43, 50]])

In [82]:
# Tranpose of matrix 
A.T

array([[1, 3],
       [2, 4]])

# Advance Array Manipulation

### Stacking array

Stacking means make 2 arrays 1. (Joining 2 arrays)

We can't stack 2 matrix. We can only use stack operations on vectors

There are 3 types of stack:
- horizontal
- vertical
- Column

In [116]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [122]:
np.vstack((a, b)) # Vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [124]:
np.hstack((a, b)) # Horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [128]:
np.column_stack((a, b)) # Column stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Splitting array

In [135]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

There can be 2 splits.
- Horizontal
- Vertical

In [142]:
np.hsplit(c, 2) # Horizontal split
# Syntax: .hsplit(array, number_of_parts)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [146]:
np.hsplit(c, 3) 

ValueError: array split does not result in an equal division

We can't split in 3 parts, we need to have equal divisions in array

This is for both horizontal and vertical split

In [156]:
np.hsplit(c, 4) 

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [158]:
np.vsplit(c, 2) # Horizontal split
# Syntax: .vsplit(array, number_of_parts)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]