# Numpy indexing and slicing of vectors

In [2]:
import numpy as np

In [3]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
# The indexing is same as list in array
arr[5] # This will give element in 5th index

16

In [15]:
arr[1:5:2] # [start_index, end_index(it should be +1 of the desired index), step]

array([12, 14])

# Numpy indexing and slicing of Matrix

In [23]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [25]:
arr[0]

array([1, 2, 3, 4, 5])

In [33]:
arr[4] # This gives the row elements, it is how we do row indexing

array([21, 22, 23, 24, 25])

Both row and colum are indexed by integers. 

In [42]:
arr[1, 1] # 1th row, 1th column

7

In [44]:
arr[0, 4] # 0th row, 4th column

5

In [49]:
arr[0:2, 1:3] # Row 0, 1 and Column 1, 2

array([[2, 3],
       [7, 8]])

For array slicing, first we need to look that elements to slice

Then, we will look the rows that we want to slice and then go for the columns, the end_index will be +1 here too.

In [54]:
arr[3:6, 3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

# Boolean Indexing

In [71]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [73]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [75]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])