In [13]:
import numpy as np

**Valid Sudoku**

In a solved sudoku, if we sum all elements of a row or a column, the sum will be 45 and also there will always be unique elements, no elements will be repeated. 

Also the 3x3 block's sum will also be 45.

In [57]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [63]:
# We want the sum of rows and columns
np.sum(s, axis = 1) # axis = 1 is for rows 

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [65]:
np.sum(s, axis = 0) # axis = 0 is for columns

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [67]:
b = np.sum(s, axis = 1)
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
        
else: 
    print("The rows are valid")

The rows are valid


In [69]:
c = np.sum(s, axis = 0)
for i in c:
    if i != 45:
        print("sudoku is not valid")
        break
        
else: 
    print("The columns are valid")

The columns are valid


In [71]:
s[0:3, 0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [73]:
s[0:3, 3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [75]:
s[0:3, 6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [89]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n = s[i:i+3, j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


**General Questions**

In [248]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [250]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [252]:
#Find the average age of students.
np.mean(data[0:6,0])

18.4

In [254]:
#Extract Math marks of all students.
data[0:6,1]

array([85, 92, 76, 65, 90])

In [256]:
#Find the highest Science mark.
np.max(data[0:6,2])

95

In [258]:
#Get details of the student who scored more than 90 in Math.
data[data[0:6,1] > 90]

array([[19, 92, 88]])

In [260]:
#Increase Math marks of all students by 5.
# data[0:6, 1] + 5 # Doesn't change the main array
data[0:6, 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [262]:
#Find how many students are younger than 19.
len(data[data[0:6, 0] < 19])

3

In [264]:
#Calculate the average marks in each subject (column-wise mean).
# maths_mean = np.mean(data[0:6, 1])
# science_mean = np.mean(data[0:6, 2])
# print(f"{maths_mean}, {science_mean}")
np.mean(data[0:6,1:3], axis=0)

array([86.6, 83.2])

In [266]:
#Get data of students who scored at least 80 in both subjects.
data[(data[0:6, 1] >= 80) & (data[0:6, 2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [274]:
#Replace all Science marks < 75 with 0.
data[0:6,2][data[0:6, 2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])