In [6]:
import numpy as np 

# Basic Array Creation

In [38]:
arr = np.array([1, 2, 3, 4]) # creates a array
arr
# basically we convert a list into the array using the numpy array method

array([1, 2, 3, 4])

In [12]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

The ARRAY has "array" written on the output but the list is just covered with "[]". There is no much difference in both.

We can have multiple data type in lists. But we need to have same data type in array.

In [31]:
b = [1, 2, 3.5, 'shubham'] # we have multiple data types here
b

[1, 2, 3.5, 'shubham']

In [33]:
np.array(b) # passing the list to convert it into array

array(['1', '2', '3.5', 'shubham'], dtype='<U32')

Here in the above output, we can see dtype='<U32' and it means everything has been converted into unicode or string

In [43]:
c = [1, 2, 4.6] # we have float and interger only this time 
np.array(c)

array([1. , 2. , 4.6])

Here, everything is converted into floats

---
There is also vector and matrix which comes from array
- array is 1D
- matrix is 2D (we have multiple rows and columns)

---
Multi-dimensional array is known as matrix. Eg: [[1, 2,3 ],[4, 5,6 ],[7, 8, 9]] 

List doesnot support multi-dimensional array. So we use NumPy to convert into matrix.

In [55]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [57]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Everything after 2D i.e. 3D, 4D, etc. are known as Tensors.

# Array generation function

For generating array, firsly we use range function but we write it as "arange" and it is just like for loop, we give start and end point and the end point should be +1 from the end point. We can also provide steps

In [70]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

We can also generate "0" using zeros function.

In [76]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

Not only array but we can generate matrix too.

In [84]:
np.zeros((4, 6)) # ((rows, columns))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Vertical are Columns and Horizontal are Rows

Like "zeros" there is "ones"

In [90]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [92]:
np.ones((6, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

---
Linear space (linspace) is the function used to have even space elements. 

We can also check the syntax and use case of the method or function by using "**Shift + Tab**"

In [97]:
np.linspace(1, 5, 2) # (start_point, end_point, number_of_elements)

array([1., 5.])

In [99]:
np.linspace(1, 5, 6)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [103]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [108]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Random generation function

We have a RANDOM library which is used to give us random elements in python,

and NUMPY provides us array,

so if both are used together than we can get random arrays

But, when we install NUMPY library, RANDOM library also gets installed automatically 

In [123]:
np.random.rand(5) # here 5 means number of elements we want

array([0.13428603, 0.13240401, 0.09939666, 0.23627013, 0.04905343])

In [119]:
np.random.rand(10)

array([0.38672692, 0.7846144 , 0.10608835, 0.85643227, 0.49659148,
       0.31604639, 0.08605037, 0.02080932, 0.94773005, 0.52885719])

We get all the values between 0 and 1.

It is because the values are normalized. The normalized values goes from 0 to 1

We can also used standarized values i.e. from -3 to +3 using "**randn**" function

In [136]:
np.random.randn(10)

array([ 0.23020755, -1.39559264,  1.35334478, -1.17908187,  0.73810124,
        1.02299131, -1.42065555, -0.36645324, -0.18123656,  0.46892229])

We can also generate integers using **randint**

In [145]:
np.random.randint(6) # Here the 6 denotes "a number between 0 to 6" not "6 numbers"

2

In [151]:
np.random.randint(10, 20, 10) # It means generate 10 number between 10 and 20
# Syntax: (start_point, end_point, numbers_count)

array([18, 16, 10, 19, 13, 16, 13, 18, 18, 13])

# Array attributes

Attributes are variables defined inside a class while Methods are functions defined inside a class.

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
# First, we need to know the shape of our array i.e. how many rows and columns are there
# and as we are exploring attributes, in attributes there is no () used
arr.shape

(3, 3)

In [19]:
# we can also check the total number of elements present in the array using size command
arr.size

9

In [25]:
# We can also check the data type of elements of array
arr.dtype

dtype('int64')

There are many attributes, we can search it accordingly when we need it, above are the most commonly used attributes.

# Array Methods

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# we can find the minimum and maximum elements from the array 
arr.min()

1

In [34]:
arr.max()

9

In [36]:
# We can get the sum of all the elements of the array 
arr.sum()

45

The **sum()** method is provided by the PYTHON but in NUMPY we can give more pararmeters in the **sum()** method, the second parameter we can give is axis

Where, axis = 0 means horizontal (It is used when we have need sum of each horizontal elements)

And, axis = 1 means vertical (It is used when we have need sum of each vertical elements) 

In [51]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [53]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [55]:
# We can also find the mean from the array
arr.mean()

5.0

In [57]:
# We can also find Standard Deviation
arr.std()

2.581988897471611

In [63]:
arr.argmax() # It gives the index of maximum element 

8

In [65]:
arr.argmin() # It gives the index of minimum element

0

# Reshaping and resizing 
It is used when we want to resize the exisiting array

In [75]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

Here, we have a 1D array or Vector, and we want to resize the array

To resize the array, first we need to call the **reshape()** method.

We need to define the new matrix in the argument. Eg: If we want 5x5 matrix then we will send (5, 5) in the argument.

But, we need to make sure that the new matrix can have all elements of the previous matrix, Eg: if we have 30 elements in the 1D matrix then we can only change it to 6x5 or 5x6. Else, we will get error

In [85]:
arr.reshape(5, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])