In [1]:
import numpy as np 

# Basic Array Creation

In [38]:
arr = np.array([1, 2, 3, 4]) # creates a array
arr
# basically we convert a list into the array using the numpy array method

array([1, 2, 3, 4])

In [12]:
a = [1, 2, 3, 4]
a

[1, 2, 3, 4]

The ARRAY has "array" written on the output but the list is just covered with "[]". There is no much difference in both.

We can have multiple data type in lists. But we need to have same data type in array.

In [31]:
b = [1, 2, 3.5, 'shubham'] # we have multiple data types here
b

[1, 2, 3.5, 'shubham']

In [33]:
np.array(b) # passing the list to convert it into array

array(['1', '2', '3.5', 'shubham'], dtype='<U32')

Here in the above output, we can see dtype='<U32' and it means everything has been converted into unicode or string

In [43]:
c = [1, 2, 4.6] # we have float and interger only this time 
np.array(c)

array([1. , 2. , 4.6])

Here, everything is converted into floats

---
There is also vector and matrix which comes from array
- array is 1D
- matrix is 2D (we have multiple rows and columns)

---
Multi-dimensional array is known as matrix. Eg: [[1, 2,3 ],[4, 5,6 ],[7, 8, 9]] 

List doesnot support multi-dimensional array. So we use NumPy to convert into matrix.

In [55]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [57]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Everything after 2D i.e. 3D, 4D, etc. are known as Tensors.

# Array generation function

For generating array, firsly we use range function but we write it as "arange" and it is just like for loop, we give start and end point and the end point should be +1 from the end point. We can also provide steps

In [70]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

We can also generate "0" using zeros function.

In [76]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

Not only array but we can generate matrix too.

In [84]:
np.zeros((4, 6)) # ((rows, columns))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Vertical are Columns and Horizontal are Rows